spring.application.name=agendador-tarefas
spring.mongodb.uri=mongodb://localhost:27017/db_agendador

usuario.url=localhost:8080
server.port=8081

jwt.secret=c3VhLWNoYXZlLXNlY3JldGEtc3VwZXItc2VndXJhLXF1ZS1kZXZlLXNlci1iZW0tbG9uZ2E=